// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Us3Yk1JgGpuOKA_DJ3oDNqARlFdBAw8',
    appId: '1:681002278624:web:5c6dd883350605fa0cba85',
    messagingSenderId: '681002278624',
    projectId: 'password-manager-13142',
    authDomain: 'password-manager-13142.firebaseapp.com',
    storageBucket: 'password-manager-13142.firebasestorage.app',
    measurementId: 'G-F59FW102PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6DqNAsjag5MxEvEBRACaILeCjwU-OwVg',
    appId: '1:681002278624:android:3165b84db7d326c20cba85',
    messagingSenderId: '681002278624',
    projectId: 'password-manager-13142',
    storageBucket: 'password-manager-13142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGkIW3iN1h8kUeEZomsnOTGMeoHOnMW3g',
    appId: '1:681002278624:ios:b38b0231894fc7e20cba85',
    messagingSenderId: '681002278624',
    projectId: 'password-manager-13142',
    storageBucket: 'password-manager-13142.firebasestorage.app',
    iosBundleId: 'com.example.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7Us3Yk1JgGpuOKA_DJ3oDNqARlFdBAw8',
    appId: '1:681002278624:web:d974f1f6b8a0c5350cba85',
    messagingSenderId: '681002278624',
    projectId: 'password-manager-13142',
    authDomain: 'password-manager-13142.firebaseapp.com',
    storageBucket: 'password-manager-13142.firebasestorage.app',
    measurementId: 'G-53XDEK2F1Z',
  );
}
